### ISSUE TITLE
Why does it fail in the workflow, but work locally?

### ISSUE THREAD

**Issue by jonasfroeller** [mxcl/xcodebuild#102]
I am confused, because the action errors, but the tests run without any issues locally.
I get a lot of errors like this:

```bash
cannot infer contextual base in reference to member 'vertical'
  
              .padding(.vertical, 15)
                       ~^~~~~~~~~~
````

What version do I have to use, to make it work?  
I only specified the ios version in the project.yml configuration but this builder needs a swift version or xcode version.

I am trying to run my tests with the following workflow:

```yml
name: propromo.ios CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    # Use macos-latest and trust this action to always work
    # This because GitHub deprecate old environments, so if you want your CI to continue to work in 5 years you need to use latest
    # This makes specifying specific xcode versions problematic however, we haven’t got a good story for this yet.

    strategy:
      matrix:
        platform:
          - iOS
        #xcode:
        #  - ^14
        # https://flatgithub.com/mxcl/.github/?filename=versions.json&sha=7f6f9803a64ce8a542970f9f04eb1b39b8b76946
        # https://github.com/actions/runner-images/blob/main/images/macos/macos-11-Readme.md#xcode
        #swift:
        #  - ^4
        #  - ^5
        scheme:
          - UnitTests
          - UiTests
        
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        brew install xcodegen

    - name: Generate Project
      run: xcodegen generate

    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ matrix.xcode }}

    # Versions:
    # https://xcodereleases.com/
    # https://developer.apple.com/support/xcode/
    - name: Xcode Tests
      uses: mxcl/xcodebuild@v2
      with:
        #xcode: ${{ matrix.xcode }}
        platform: ${{ matrix.platform }}
        # swift: ${{ matrix.swift }}
        action: test # `build`
        code-coverage: false # default = `false`
        warnings-as-errors: false # default = `false`
        scheme: ${{ matrix.scheme }}
```

This is my project.yml file:

```yml
name: Propromo

settings:
  GENERATE_INFOPLIST_FILE: YES
  MARKETING_VERSION: 0.0.0
  CURRENT_PROJECT_VERSION: 0.0.0
options:
  bundleIdPrefix: com.propromo
packages:
  Alamofire:
    url: https://github.com/Alamofire/Alamofire
    majorVersion: 5.5.0
targets:
  Propromo:
    type: application
    platform: iOS
    deploymentTarget: "17.0"

    sources:
      - path: ./core/features
        group: propromo
      - path: ./core/resources
        group: propromo
      - path: ./core/services
        group: propromo

    dependencies:
      - package: Alamofire

    # Link with its target to run with cmd+u
    scheme:
      gatherCoverageData: true
      testTargets:
        - name: UnitTests
          parallelizable: true
          randomExecutionOrder: true

    scheme:
      gatherCoverageData: true
      testTargets:
        - name: UiTests
          parallelizable: true
          randomExecutionOrder: true

  UnitTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: ./core/tests/unit
        group: propromo

    # Link with ./core target
    dependencies:
      - target: Propromo
      
    # Create a new scheme that will be linked and configured for test purposes
    scheme:
      gatherCoverageData: true
      testTargets:
        - name: UnitTests
          parallelizable: true
          randomExecutionOrder: true

  UiTests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: ./core/tests/ui
        group: propromo

    # Link with ./core target
    dependencies:
      - target: Propromo
      
    # Create a new scheme that will be linked and configured for test purposes
    scheme:
      gatherCoverageData: true
      testTargets:
        - name: UiTests
          parallelizable: true
          randomExecutionOrder: true
```
