### ISSUE TITLE
Running tests using stable Xcode selects beta simulator

### ISSUE THREAD

**Issue by NachoSoto** [mxcl/xcodebuild#113]
From the docs:
> We figure out the the simulator destination for you automatically. Stop specifying fragile strings like platform=iphonesimulator,os=14.5,name=iPhone 12 that will break when Xcode updates next week.

Which is a great feature... however, this:
```yaml
- uses: mxcl/xcodebuild@v3
  with:
    platform: iOS
    xcode: '~16.0'
    action: test
    configuration: 'debug'
```

Should not run on an iOS 18.1 beta simulator just because it's installed.
