### ISSUE TITLE
Unable to find Xcode version with latest GitHub Actions update

### ISSUE THREAD

**Issue by NachoSoto** [mxcl/xcodebuild#124]
The [latest image](https://github.com/actions/runner-images/blob/macos-15-arm64/20250331.1175/images/macos/macos-15-arm64-Readme.md#xcode) added Xcode 16.3, and now for some reason this action can no longer find `16.3` or `16.2`.

This is what `ls -ad /Applications/Xcode*` prints:
```
/Applications/Xcode_16.0.0.app /Applications/Xcode_16.0.app /Applications/Xcode_16.1.0.app /Applications/Xcode_16.1.app /Applications/Xcode_16.2.0.app /Applications/Xcode_16.2.app /Applications/Xcode_16.3.0.app /Applications/Xcode_16.3.app /Applications/Xcode_16.3_Release_Candidate_2.app /Applications/Xcode_16.app
```

However doing this:
```yaml
- uses: mxcl/xcodebuild
  name: "Select Xcode"
  with:
    xcode: ~16.3 # Also fails with ~16.2
    action: none
```

Results in
> Error: Error: No Xcode ~> >=16.3.0 <16.4.0-0
