### ISSUE TITLE
Doesn't work with `ruby/setup-ruby`'s `bundler-cache: true`

### ISSUE THREAD

**Issue by quad** [mxcl/xcodebuild#84]
We've got a build that looks something like:

```yaml
- uses: ruby/setup-ruby@v1
  with:
    bundler-cache: true

- uses: mxcl/xcodebuild@v1
  with:
    working-directory: app/ios
    scheme: AppTests
    platform: iOS
```

When there's no `bundler-cache`, the build succeeds. When `bundler-cache` is true, the `xcodebuild` step fails:

```javascript
xcodebuild test
  Error: spawn xcpretty ENOENT
      at Process.ChildProcess._handle.onexit (node:internal/child_process:282:[19](https://github.com/squareup/wallet/actions/runs/3318014846/jobs/5481488702#step:7:20))
      at onErrorNT (node:internal/child_process:477:16)
      at processTicksAndRejections (node:internal/process/task_queues:83:[21](https://github.com/squareup/wallet/actions/runs/3318014846/jobs/5481488702#step:7:22))
```

I lightly suspect it's because [`setup-ruby` changes the bundle configuration](https://github.com/ruby/setup-ruby/blob/0a29871fe2b0200a17a4497bae54fe5df0d973aa/bundler.js#L144-L157). Is there a way for `xcodebuild` to detect that `xcpretty` was installed via `bundle` and to run `bundle exec xcpretty` instead?
