### ISSUE TITLE
How to specify the output dir ?

### ISSUE THREAD

**Issue by wangzhaode** [mxcl/xcodebuild#85]
When I used this action build a iOS project using below code:
```
  - uses: mxcl/xcodebuild@v1
    with:
      platform: iOS
      action: build
      configuration: release
      working-directory: project/ios
      scheme: XXX
```
I get the below log:
```
▸ xcodebuild build
.....
▸ Touching XXX.framework (in target 'XXX' from project 'XXX')
▸ Build Succeeded
```
Now i want to get `MNN.framework` and upload, but i can't find a way to set the `output dir`
